<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- include the ros2_control wrapper and cylinder helper -->
  <xacro:include filename="$(find robotiq_hande_description)/urdf/robotiq_hande_gripper.ros2_control.xacro"/>
  <xacro:include filename="$(find robotiq_hande_description)/urdf/cylinder_inertial.xacro"/>

  <!--
    Macro parameters:
      name             -> slider/joint name ("gripper")
      prefix           -> link/joint prefix ("" for no prefix)
      parent           -> parent link (e.g. "grip_mount_link")
      grip_pos_min/max -> min/max opening
      tty, baudrate…   -> hardware params (ignored with fake_hardware)
      use_fake_hardware-> true for simulation
  -->
  <xacro:macro name="robotiq_hande_gripper" params="
      name
      prefix
      parent
      grip_pos_min
      grip_pos_max
      tty
      baudrate
      parity
      data_bits
      stop_bit
      slave_id
      use_fake_hardware">

    <!-- ros2_control block (fake hardware by default) -->
    <xacro:robotiq_hande_ros2_control
      name="${name}"
      prefix="${prefix}"
      grip_pos_min="${grip_pos_min}"
      grip_pos_max="${grip_pos_max}"
      tty="${tty}"
      baudrate="${baudrate}"
      parity="${parity}"
      data_bits="${data_bits}"
      stop_bit="${stop_bit}"
      slave_id="${slave_id}"
      use_fake_hardware="${use_fake_hardware}"
    />

    <!-- IO coupler -->
    <xacro:arg name="coupler_height" default="0.011"/>
    <xacro:arg name="coupler_shell_height" default="0.0169"/>
    <xacro:arg name="coupler_parent_cutoff" default="0.003"/>
    <xacro:arg name="coupler_hande_cutoff" default="0.0029"/>
    <xacro:arg name="hande_height" default="0.099"/>
    <xacro:arg name="hande_radius" default="0.0375"/>

    <joint name="${prefix}robotiq_hande_coupler_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child  link="${prefix}robotiq_hande_coupler"/>
    </joint>
    <link name="${prefix}robotiq_hande_coupler">
      <visual>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/io_coupler.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${$(arg coupler_shell_height)/2 - $(arg coupler_parent_cutoff)}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="$(arg coupler_shell_height)" radius="${$(arg hande_radius) + 0.001}"/>
        </geometry>
      </collision>
      <xacro:__robotiq_hande_cylinder_inertial
        radius="$(arg hande_radius)"
        height="$(arg coupler_shell_height)"
        mass="0.119">
        <origin xyz="0 0 ${($(arg coupler_shell_height)/2) - $(arg coupler_parent_cutoff)}" rpy="0 0 0"/>
      </xacro:__robotiq_hande_cylinder_inertial>
    </link>

    <!-- Hand body -->
    <joint name="${prefix}robotiq_hande_base_joint" type="fixed">
      <origin xyz="0 0 $(arg coupler_height)" rpy="0 0 0"/>
      <parent link="${prefix}robotiq_hande_coupler"/>
      <child  link="${prefix}robotiq_hande_link"/>
    </joint>
    <link name="${prefix}robotiq_hande_link">
      <visual>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/hande.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${($(arg hande_height) + $(arg coupler_hande_cutoff) + 0.005)/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${$(arg hande_height) + $(arg coupler_hande_cutoff) + 0.005}"
                    radius="${$(arg hande_radius) + 0.001}"/>
        </geometry>
      </collision>
      <xacro:__robotiq_hande_cylinder_inertial
        radius="$(arg hande_radius)"
        height="$(arg hande_height)"
        mass="0.86387">
        <origin xyz="0 0 ${$(arg hande_height)/2}" rpy="0 0 0"/>
      </xacro:__robotiq_hande_cylinder_inertial>
    </link>

    <!-- 1) master “gripper” slider joint -->
    <joint name="${name}" type="prismatic">
      <origin xyz="0 0 $(arg hande_height)" rpy="0 0 0"/>
      <parent link="${prefix}robotiq_hande_link"/>
      <child  link="${name}_finger"/>
      <axis xyz="1 0 0"/>
      <limit effort="130"
             lower="${grip_pos_min}"
             upper="${grip_pos_max}"
             velocity="0.15"/>
    </joint>
    <link name="${name}_finger">
      <visual>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/finger_collision.dae"/>
        </geometry>
      </collision>
    </link>

    <!-- 2) mimic joint, with identical limits -->
    <joint name="${name}_mimic" type="prismatic">
      <origin xyz="0 0 $(arg hande_height)" rpy="0 0 0"/>
      <parent link="${prefix}robotiq_hande_link"/>
      <child  link="${name}_finger_mimic"/>
      <axis xyz="-1 0 0"/>
      <limit effort="130"
             lower="${grip_pos_min}"
             upper="${grip_pos_max}"
             velocity="0.15"/>
      <mimic joint="${name}" multiplier="1" offset="0"/>
    </joint>
    <link name="${name}_finger_mimic">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://robotiq_hande_description/meshes/finger_collision.dae"/>
        </geometry>
      </collision>
    </link>

    <!-- final fixed end link -->
    <joint name="${prefix}robotiq_hande_end_joint" type="fixed">
      <origin xyz="0 0 ${$(arg hande_height) + 0.0465}" rpy="0 0 0"/>
      <parent link="${prefix}robotiq_hande_link"/>
      <child  link="${prefix}robotiq_hande_end"/>
    </joint>
    <link name="${prefix}robotiq_hande_end"/>

  </xacro:macro>
</robot>

